services:
  - type: web
    name: omnifetch-api
    runtime: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg python3 python3-pip
      pip3 install -U yt-dlp
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FFMPEG_PATH
        value: /usr/bin/ffmpeg
      - key: YTDLP_PATH
        value: /usr/local/bin/yt-dlp
